language: python

python: '3.6'
sudo: required


env:
  global:
    - AWS_BUCKET_REGION=eu-west-1
    - AWS_DEFAULT_REGION=eu-west-1

matrix:
  include:
    - python: '3.6'
      env:
        - APP=bar.lambda
        - PYTHONPATH=$TRAVIS_BUILD_DIR:$PYTHONPATH
    - python: '3.6'
      env:
        - APP=foo.lambda
        - PYTHONPATH=$TRAVIS_BUILD_DIR:$PYTHONPATH
        - python: '3.6'
      env:
        - APP=example.project/src/other.lambda
        - PYTHONPATH=$TRAVIS_BUILD_DIR/$APP:$PYTHONPATH
        - python: '3.6'

services:
  - docker

before_install:
  - cd $APP
  - docker run -p 4567-4578:4567-4578 -e SERVICES=kinesis,s3 --name="local_aws" localstack/localstack & sleep 60


install:
  - pip install python-dateutil rollbar botocore==1.9.1 boto3==1.6.0 localstack

script:
  - pytest -s
  #- docker stop local_aws; docker rm local_aws

before_deploy:
  - $TRAVIS_BUILD_DIR/.travis/lib_packaging.sh

deploy:
  provider:          s3
  access_key_id:     $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket:            $AWS_BUCKET
  region:            $AWS_BUCKET_REGION
  upload-dir:        $TRAVIS_REPO_SLUG/$APP/$TRAVIS_COMMIT
  acl:               private
  local_dir:         dest
  skip_cleanup:      true
  on:
    all_branches:    true
