language: python

python: '3.6'
sudo: false

env:
  global:
    - AWS_BUCKET_REGION=eu-west-1
    - AWS_DEFAULT_REGION=eu-west-1

matrix:
  include:
    - python: '3.6'
      env:
        - APP=bar.lambda
        - PYTHONPATH=$TRAVIS_BUILD_DIR:$PYTHONPATH
    - python: '3.6'
      env:
        - APP=foo.lambda
        - PYTHONPATH=$TRAVIS_BUILD_DIR:$PYTHONPATH


services:
  - docker

before_install:
  - cd $APP
  - docker run --name="kinesis_mock" -d -t -p 4567:4567 dlsniper/kinesalite:1.11.4

before_deploy:
  - ../.travis/lib_packaging.sh

install:
  - pip install python-dateutil rollbar boto3

script:
  - pytest


deploy:
  provider:          s3
  access_key_id:     $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket:            $AWS_BUCKET
  region:            $AWS_BUCKET_REGION
  upload-dir:        $TRAVIS_REPO_SLUG/$APP/$TRAVIS_COMMIT
  acl:               private # keep them private
  local_dir:         dest
  skip_cleanup:      true
  on:
    all_branches:    true
