language: python

python: '3.6'
sudo: false

env:
  global:
    - AWS_DEFAULT_REGION=eu-west-1
    - PYTHONPATH=$TRAVIS_BUILD_DIR:$PYTHONPATH

matrix:
  include:
    - python: '3.6'
      env: APP=bar.lambda
    - python: '3.6'
      env: APP=foo.lambda

before_install:
  - cd $APP

before_deploy:
  - bash .travis/lib_packaging


script:
  - return 0


deploy:
  provider:          s3
  access_key_id:     $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket:            $AWS_BUCKET
  region:            $AWS_BUCKET_REGION
  upload-dir:        $TRAVIS_REPO_SLUG/$APP/$TRAVIS_COMMIT
  acl:               private # keep them private
  local_dir:         dest
  skip_cleanup:      true
  on:
    all_branches:    true