language: python

python: '3.6'
sudo: false

env:
  global:
    - AWS_BUCKET_REGION=eu-west-1
    - AWS_DEFAULT_REGION=eu-west-1

matrix:
  include:
    - python: '3.6'
      env:
        - APP=bar.lambda
        - PYTHONPATH=$TRAVIS_BUILD_DIR:$PYTHONPATH
    - python: '3.6'
      env:
        - APP=foo.lambda
        - PYTHONPATH=$TRAVIS_BUILD_DIR:$PYTHONPATH


services:
  - docker

before_install:
  - cd $APP
  - pip install localstack
  - docker run -p 4567-4578:4567-4578 -p 8080:8080 atlassianlabs/localstack & sleep 120

before_deploy:
  - ../.travis/lib_packaging.sh

install:
  - pip install python-dateutil rollbar boto3==1.6.0


script:
  - pytest -s


deploy:
  provider:          s3
  access_key_id:     $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket:            $AWS_BUCKET
  region:            $AWS_BUCKET_REGION
  upload-dir:        $TRAVIS_REPO_SLUG/$APP/$TRAVIS_COMMIT
  acl:               private
  local_dir:         dest
  skip_cleanup:      true
  on:
    all_branches:    true
